driver/urls.py
from django.urls import path
from driver import views


app_name = '<drivers>'

urlpatterns = [
    path('', views.driver, name='driver'),
    path('trip/', views.trip, name='trip'),
    path('inspection/', views.inspection, name='inspection'),
    path('refilling/', views.refilling, name='refilling'),
    path('maintenance/', views.maintenance, name='maintenance')
]

fleet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('transport/', include('main.urls', namespace='main')),
    path('driver/', include('driver.urls', namespace='drivers')),
    path('hr/', include('humanresource.urls', namespace='hr')),
    path('gpsa/', include('gpsa.urls')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('workshop/', include('workshop.urls', namespace='workshop')),


]

gpsa/urls.py
from django.urls import path
from gpsa import views

urlpatterns = [
    path('', views.gpsa, name='gpsa'),
]

main/urls.py
from django.urls import path, include
from main import views
from staff.models import Request


app_name = "<main>"

urlpatterns = [
    # path('', include(('main.urls', 'main'), namespace='main')),
    path('', views.transport, name='transport'),
    path('requests', views.requests, name='requests'),
    path('requests/edit/<request_id>', views.edit_request, name='edit_request'),
    path('Vehicle Status/', views.status, name='status'),
    path('Vehicle Status/edit/<status_id>', views.edit_status, name='edit_status'),
    path('Filling Requests/', views.filling, name='filling'),
    path('Filling Requests/edit/<filling_id>', views.edit_filling, name='edit_filling'),
    path('drivers/', views.driver, name='driver'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('maintenance/edit/<main_id>', views.edit_main, name='edit_main'),
    path('Driver/Assign/edit/<driver_id>', views.assign, name='assign'),
    path('Driver/Set Status/edit/<set_id>', views.aval, name='aval'),
    path('delete/<driver_id>', views.delete_drv, name='delete_drv'),
]

main/models.py
from django.db import models
from driver.models import Vehicle



# Create your models here.
class VehicleStatus(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default='Available')
    assigned = models.CharField(max_length=50)

    def __str__(self):
        return str(self.vehicle) + self.assigned + self.status

driver/forms.py
from django import forms
from driver.models import Inspection, Refilling


class InspectionForm(forms.ModelForm):
    class Meta:
        model = Inspection
        fields = '__all__'


class RefillingForm(forms.ModelForm):
    class Meta:
        model = Refilling
        fields = '__all__'

main/forms.py
from django import forms
from driver.models import Vehicle, Driver


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = '__all__'

driver/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from driver.models import Inspection, Refilling, Driver, Vehicle
from accounts.decorators import driver_required
from django.http import HttpResponse
from driver.forms import InspectionForm, RefillingForm
from staff.models import Request
from workshop.models import Maintainance
from workshop.forms import MaintenanceForm
from accounts.models import User


# Create your views here.

def driver(request):
    return render(request, 'driver_index.html', {})


def trip(request):
    tripss = Request.objects.all()
    mapbox_access_token = 'pk.eyJ1IjoiaWRhdmVyczk4IiwiYSI6ImNrcXBzZWxmczA4Mm8ydnEzMXR3emt3eXcifQ.d-QVNcLt_5acuWmgUpBPTA'
    return render(request, 'trip.html', {'trip': tripss, 'mapbox_access_token': mapbox_access_token})


def inspection(request):
    if request.method == 'POST':
        form = InspectionForm(request.POST)

        Inspection.objects.create(date=request.POST['date'], license=request.POST['number'],
                                  driver=request.POST['driver'], odometer=request.POST['odometer'],
                                  defect=request.POST['defect'])

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
        return redirect('drivers:inspection')

    inspect = Inspection.objects.all()
    tripss = Vehicle.objects.all()
    drvr = Driver.objects.all()

    return render(request, 'inspection.html', {'insp': inspect, 'vehicle': tripss, 'driver': drvr})


def refilling(request):
    if request.method == 'POST':
        form = RefillingForm(request.POST)
        Refilling.objects.create(towards=request.POST['kwenda'], fuel=request.POST['aina'],
                                 liters=request.POST['kiasi'], vehicle=request.POST['gari'], driver=request.POST['driver'])
        if form.is_valid():
            instance = form.save(commit=False)
            instance.sent_by = request.user
        return redirect('drivers:refilling')
    users = User.objects.all()
    refill = Refilling.objects.all()
    drv = Driver.objects.all()
    vhc = Vehicle.objects.all()

    return render(request, 'refilling.html', {'refill': refill, 'driver': drv, 'vehicle': vhc, 'users': users})


def maintenance(request):
    if request.method == 'POST':
        form = MaintenanceForm(request.POST)
        Maintainance.objects.create(date=request.POST['date'], vehicle=request.POST['number'],
                                    driver=request.POST['driver'],
                                    mtype=request.POST['type'], description=request.POST['description'])
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
        return redirect('drivers:maintenance')
    else:
        tripss = Vehicle.objects.all()
        drvr = Driver.objects.all()
        return render(request, 'drmaintenance.html', {'vehicle': tripss, 'driver': drvr})

main/views.py
from django.shortcuts import render, redirect
from staff.models import Request
from staff.forms import RequestForm
from driver.models import Refilling, Vehicle, Driver, Locations
from workshop.models import Maintainance, MajorMaintainance
from accounts.models import User
from main.models import VehicleStatus
from driver.forms import RefillingForm
from workshop.forms import MaintenanceForm
from accounts.decorators import transport_required
from django.http import HttpResponse
from main.forms import VehicleForm, DriverForm
from django.core.mail import send_mail
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
import random


# Create your views here.

def transport(request):
    mapbox_access_token = 'pk.eyJ1IjoiaWRhdmVyczk4IiwiYSI6ImNrcXBzZWxmczA4Mm8ydnEzMXR3emt3eXcifQ.d-QVNcLt_5acuWmgUpBPTA'
    return render(request, 'index.html', {'mapbox_access_token': mapbox_access_token})


def requests(request):
    tripss = Request.objects.all()
    return render(request, 'request.html', {'trips': tripss})


def edit_request(request, request_id):
    if request.method == "POST":

        req = Request.objects.get(pk=request_id)
        form = RequestForm(request.POST or None, instance=req)
        # Request.objects.update(driver=request.POST['driver'])
        Request.objects.filter(id=request_id).update(driver=request.POST['driver'], approved_by=request.POST['trans'])
        sms = request.POST['driver']
        number = Request.objects.raw('select phone from driver_assigned')
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            send_mail(
                'Trip FeedBack',
                'Your Trip information is already posted login to check status',
                'davidrobert785@gmail.com',
                ['davidrobert10@ymail.com'],
                fail_silently=False
            )

        return redirect('main:requests')
    else:
        req_obj = Request.objects.get(pk=request_id)
        drv = Driver.objects.all()
        users = User.objects.all()
        print(request_id)
        return render(request, 'edit.html', {'req_obj': req_obj, 'driver': drv, 'users': users})


def status(request):
    if request.method == "POST":

        form = VehicleForm(request.POST)
        print(form)
        Vehicle.objects.create(model=request.POST['vmodel'], license=request.POST['licence'],
                               fuel_type=request.POST['fuel'],
                               manufacturer=request.POST['make'], color=request.POST['vcolor'],
                               transmission=request.POST['trans'], seats=request.POST['vseat'],
                               status=request.POST['status'],
                               body=request.POST['type'], last_refill=request.POST['refill'],
                               maintenance_record=request.POST['vmaint'],
                               operability=request.POST['op'], mileage=request.POST['milleage'])
        if form.is_valid():
            form.save()
        return redirect('main:status')
    else:
        tripss = Vehicle.objects.all()
        loc = [Locations.objects.all().last()]

        # last_date = loc.id
        return render(request, 'vehStatus.html', {'trips': tripss, 'loc': loc})


def edit_status(request, status_id):
    if request.method == "POST":

        stat = VehicleStatus.objects.get(pk=status_id)
        form = VehicleForm(request.POST or None, instance=stat)
        VehicleStatus.objects.filter(id=status_id).update(status=request.POST['status'])
        if form.is_valid():
            form.save()
        return redirect('main:status')
    else:
        stat_obj = VehicleStatus.objects.get(pk=status_id)
        print(status_id)
        return render(request, 'edit_status.html', {'stat': stat_obj})


def filling(request):
    tripss = Refilling.objects.all()
    return render(request, 'filling requests.html', {'trips': tripss})


def edit_filling(request, filling_id):
    if request.method == "POST":
        fill = Refilling.objects.get(pk=filling_id)
        form = RefillingForm(request.POST or None, instance=fill)
        Refilling.objects.filter(id=filling_id).update(number=request.POST['namba'], approved=request.POST['transport'])
        if form.is_valid():
            instance = form.save(commit=False)
            instance.received_by = request.user
        return redirect('main:filling')
    else:
        fill_obj = Refilling.objects.get(pk=filling_id)
        tro = User.objects.all()
        number = random.randint(1, 798)
        return render(request, 'edit_filling.html', {'fill': fill_obj, 'num': number, 'users': tro})


def driver(request):

    if request.method == 'POST':
        form = DriverForm(request.POST or None, request.FILES or None)

        Driver.objects.create(driver_name=request.POST['fname'],
                              vehicle=request.POST['number'], status=request.POST['status'],
                              phone=request.POST['phone'], added_by=request.POST['added_by'])
        if form.is_valid():
            form.save()

        return redirect('main:driver')
    else:
        tripss = Driver.objects.all()

        vehicle = Vehicle.objects.all()

        users = User.objects.all()
        return render(request, 'driver.html', {'trips': tripss, 'vehicle': vehicle, 'users': users})


def maintenance(request):
    main = Maintainance.objects.all()
    return render(request, 'maintenance.html', {'main': main})


def edit_main(request, main_id):
    if request.method == "POST":
        main = Maintainance.objects.get(pk=main_id)
        form = MaintenanceForm(request.POST or None, instance=main)
        Maintainance.objects.filter(id=main_id).update(transport=request.POST['transport'])
        if form.is_valid():
            form.save()
        return redirect('main:maintenance')
    else:
        main_obj = Maintainance.objects.get(pk=main_id)
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'editmain.html', {'main': main_obj, 'user': tro})


def assign(request, driver_id):
    if request.method == "POST":
        drv = Driver.objects.get(pk=driver_id)
        form = DriverForm(request.POST or None, instance=drv)
        Driver.objects.filter(id=driver_id).update(vehicle=request.POST['vehicle'])
        if form.is_valid():
            form.save()
        return redirect('main:driver')
    else:
        drv_obj = Driver.objects.get(pk=driver_id)
        veh = Vehicle.objects.all()
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'assign.html', {'drv': drv_obj, 'user': tro, 'veh': veh})


def aval(request, set_id):
    if request.method == "POST":
        drv = Driver.objects.get(pk=set_id)
        form = DriverForm(request.POST or None, instance=drv)
        Driver.objects.filter(id=set_id).update(status=request.POST['status'])
        if form.is_valid():
            form.save()
        return redirect('main:driver')
    else:
        drv_obj = Driver.objects.get(pk=set_id)
        veh = Vehicle.objects.all()
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'setAvailable.html', {'drv': drv_obj, 'user': tro, 'veh': veh})


def delete_drv(request, driver_id):
    drv = Driver.objects.get(pk=driver_id)
    drv.delete()
    return redirect('main:driver')

main/templates/assign.html
{% extends 'basetr.html' %}

{% block title %}
        <title> FMS | Driver</title>
{% endblock %}


{% block content %}

        <section>

        <form method="post">
            {% csrf_token %}
            <h3> Assign Vehicle for {{ drv.driver_name }} </h3>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="facility_opt">Assign Vehicle</label>
                                  <select class="form-control" name="vehicle">
                                     <option value="" disabled selected>Vehicle</option>

                                    {% for obj in veh %}
                                        <option>{{ obj.license }}</option>
                                     {% endfor %}
                                <option>Not Assigned</option>
                                </select>
                                </div>
                            </div>
{#                                    <div class="col-sm-6">#}
{#                                        <div class="form-group">#}
{#                                            <label for="facility_opt">Driver Status</label>#}
{#                                                <select id="facility_opt" class="form-control" name="status">#}
{#                                                    <option value="" disabled selected>Select</option>#}
{#                                                        {% for obj in vehicle %}#}
{#                                                        {% if obj.status == 'available' %}#}
{#                                                    <option>Available</option>#}
{#                                                    <option>Unavailable</option>#}
{#                                                    {% endif %}#}
{#                                                    {% endfor %}#}
{#                                                        </select>#}
{#                                        </div>#}
{#                                    </div>#}
                        </div>
        <div><button type="submit" class="btn btn-primary">Assign</button></div>

        </form>


        </section>

{% endblock %}

main/templates/driver.html
{% extends 'basetr.html' %}

{% block title %}
    <title>Drivers - Fleet</title>
{% endblock %}

{% block content %}

{#     <div id='map' style='width: 100%; height: 300px;'></div>#}
{#                        <script>#}
{#                          mapboxgl.accessToken = 'pk.eyJ1IjoiaWRhdmVyczk4IiwiYSI6ImNrcXBzZWxmczA4Mm8ydnEzMXR3emt3eXcifQ.d-QVNcLt_5acuWmgUpBPTA';#}
{#                          var map = new mapboxgl.Map({#}
{#                            container: 'map',#}
{#                            style: 'mapbox://styles/mapbox/streets-v11'#}
{#                          });#}
{#                        </script>#}

                    <div class="card-body">
                   <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
                  Register Driver
                </button>
                </div>

                <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Add Driver</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form action="" method="POST" class="form clearfix newform" id="driverform">
                                    {% csrf_token %}

                            <div class="row">
                                    <div class="col-sm-6">
                                          <div class="form-group">
                                             <label for="facility_opt">Driver</label>
                                              <select id="facility_opt" class="form-control" name="fname">
                                                  <option value="" disabled selected>Select</option>
                                                {% for obj in users %}
                                                {% if obj.user_type == 2 %}
                                                    <option value="{{ obj.username }}">{{ obj.username }}</option>
                                                    {% endif %}
                                                        {% endfor %}

                                                            </select>
                                                        </div>
                                                    </div>

                            <div class="col-sm-6">
                                          <div class="form-group">
                                            <label for="phone">Contact No.</label>
                                            <input type="tel" name="phone" id="phone" class="form-control" placeholder="Phone number" maxlength="11" required>
                                          </div>
                                        </div>
                            </div>

                              <div class="row">
                                        <div class="col-sm-6">
                                          <div class="form-group">
                                            <label for="facility_opt">Assigned Vehicle</label>
                                            <select id="facility_opt" class="form-control" name="number">
                                            <option value="" disabled selected>Select</option>
                                                 {% for obj in vehicle %}
                                                    {% if obj.status == 'available' %}
                                            <option value="{{ obj.license }}">{{ obj.license }}</option>
                                                    {% endif %}
                                                    {% endfor %}
                                            <option>Not Assigned</option>
                                                        </select>
                                                            </div>
                                                                </div>
                                                <div class="col-sm-6">
                                          <div class="form-group">
                                            <label for="facility_opt">Approved by</label>
                                            <select id="facility_opt" class="form-control" name="added_by" required>
                                            <option value="" disabled selected>Select</option>
                                                 {% for obj in users %}
                                                    {% if user.get_username == obj.username %}
                                            <option value="{{ obj.username }}">{{ obj.username }}</option>
                                                    {% endif %}
                                                    {% endfor %}

                                                        </select>
                                                            </div>
                                                                </div>
                              </div>

                            <div class="row">
                                        <div class="col-sm-6">
                                          <div class="form-group">
                                            <label for="">Driver Status: </label>
                                            <div class="radio-group">
                                            <label for="status-available">Available</label>
                                            <input type="radio" id="status-available"  name="status" value="available" checked>
                                            <label for="status-unavailable">Unavailable</label>
                                            <input type="radio" name="status"  id="status-unavailable" value="unavailable">
                                                </div>
                                          </div>


                                        </div>
                            </div>




                          <div class="modal-footer justify-content-between">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Add Driver</button>
            </div>

                        </form>
            </div>

          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>

                <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>

                                        <th>Driver Name</th>
                                        <th>Contact No.</th>
                                        <th>Assigned Vehicle</th>
                                        <th>Status</th>
                                        <th>Registered By</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                            <tbody>
                            {% for obj in trips %}
                            <tr>

                                 <td>{{ obj.driver_name }}</td>
                                 <td>{{ obj.phone }}</td>
                                 <td><a href="{% url 'main:assign' obj.id %}">{{ obj.vehicle }}</a></td>
                                <td>{{ obj.status }}</td>
                                <td>{{ obj.added_by }}</td>
                            <td>
                            <a href="{% url 'main:aval' obj.id %}">
                            <i class="far fa-edit"></i></a></td>
                            <td>
                            <a href="{% url 'main:delete_drv' obj.id %}">
                            <i class="far fa-trash-alt"></i></a></td>
                  </tr>



                            {% endfor %}
                            </tbody>
                <tfoot>
                <tr>

                                        <th>Driver Name</th>
                                        <th>Contact No.</th>
                                        <th>Assigned Vehicle</th>
                                        <th>Status</th>
                                        <th>Registered By</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                </tr>
                </tfoot>
                </table>
                </div>
{% endblock %}

  <form action="" method="POST" class="form clearfix newform" id="driverform">
                                    {% csrf_token %}
                            <span class="in_form">
                                <label for="employee">Employee No.</label>
                                <input type="tel" name="employee" id="employee" placeholder="0001111" maxlength="7" required>
                            </span>

                            <span class="in_form">
                                <label for="fname">First Name</label>
                                <input type="text" name="fname" id="fname" placeholder="First Name" required>
                            </span>

                             <span class="in_form">
                                <label for="facility_opt">Assigned Vehicle</label>
                                <select id="facility_opt" name="number">
                                    <option value="" disabled selected>Select</option>
                                    {% for obj in vehicle %}
                                    <option value="{{ obj.license }}">{{ obj.license }}</option>
                                         {% endfor %}
                                </select>
                            </span>
                                 <span class="in_form">
                                <label for="facility_opt">Assigned Staff</label>
                                <select id="facility_opt" name="staff">
                                    <option value="" disabled selected>Select</option>
                                    {% for obj in staff %}
                                        {% if obj.driver == 'Not Assigned' %}
                                    <option value="{{ obj.staff_id }}">{{ obj.staff_id }}</option>

                                        {% endif %}
                                         {% endfor %}
                                <option>Not Assigned</option>
                                </select>
                            </span>
                            <span class="in_form">
                                <label for="phone">Contact No.</label>
                                <input type="tel" name="phone" id="phone" placeholder="Phone number" maxlength="11" required>
                            </span>



                            <span class="in_form">
                                <label for="">Driver Status: </label>
                                <div class="radio-group">
                                    <label for="status-available">Available</label>
                                    <input type="radio" id="status-available" name="status" value="available" checked>
                                    <label for="status-unavailable">Unavailable</label>
                                    <input type="radio" name="status" id="status-unavailable" value="unavailable">
                                </div>
                            </span>


                            <span class="form__btn--group">
                                <input type="reset" value="reset" class="btn btn-small btn-reset">
                                <input type="submit" value="Add Driver" class="btn">
                            </span>

                        </form>

main/templates/maintenance.html
{% extends 'basetr.html' %}

{% block title %}
    <title>Maintenance - Fleet</title>
{% endblock %}

{% block content %}

     <div class="container-fluid">
                         <div class="card">

              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                          <thead>
                                <tr>
                                <th >Date</th>
                                  <th>Driver</th>
                                  <th>Vehicle</th>
                                  <th>Type</th>
                                    <th>Status</th>
                                    <th>Update</th>


                                </tr>
                              </thead>
                              <tbody>
                               {% for obj in main %}
                       <tr>
{#                                  <th scope="row">{{ obj.id }}</th>#}
                           <td><a href="">{{ obj.date }}</a></td>
                                  <td>{{ obj.driver }}</td>
                                  <td>{{ obj.vehicle }}</td>
                                   <td>{{ obj.mtype }}</td>
                                    <td>{{ obj.transport }}</td>


                           <td>
                                <a href="{% url 'main:edit_main' obj.id %}" class="opt">
                                <i class="ion-edit btn-small"></i>
                                </a>
                           </td>

                                </tr>
                    {% endfor %}
                              </tbody>
               <tfoot>
               <tr>
                                <th >Date</th>
                                  <th>Driver</th>
                                  <th>Vehicle</th>
                                  <th>Type</th>
                                    <th>Status</th>
                                    <th>Update</th>
               </tr>
               </tfoot>
  ...
                </table>
                </div>
            </div>
        </div>

{% endblock%}