fleet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('transport/', include('main.urls', namespace='main')),
    path('driver/', include('driver.urls', namespace='drivers')),
    path('hr/', include('humanresource.urls', namespace='hr')),
    path('gpsa/', include('gpsa.urls')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('workshop/', include('workshop.urls', namespace='workshop')),


]

gpsa/urls.py
from django.urls import path
from gpsa import views

urlpatterns = [
    path('', views.gpsa, name='gpsa'),
]

humanresource/urls.py
from django.urls import path
from humanresource import views

app_name = "<hr>"

urlpatterns = [
    path('', views.human, name='human'),
    path('refilling requests', views.refill, name='refill'),
    path('refilling/edit/<request_id>', views.edit_request, name='edit_request'),
    path('maintenance', views.maintenance, name='maintenance')
]

main/urls.py
from django.urls import path, include
from main import views
from staff.models import Request


app_name = "<main>"

urlpatterns = [
    # path('', include(('main.urls', 'main'), namespace='main')),
    path('', views.transport, name='transport'),
    path('requests', views.requests, name='requests'),
    path('requests/edit/<request_id>', views.edit_request, name='edit_request'),
    path('Vehicle Status/', views.status, name='status'),
    path('Vehicle Status/edit/<status_id>', views.edit_status, name='edit_status'),
    path('Filling Requests/', views.filling, name='filling'),
    path('Filling Requests/edit/<filling_id>', views.edit_filling, name='edit_filling'),
    path('drivers/', views.driver, name='driver'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('maintenance/edit/<main_id>', views.edit_main, name='edit_main'),
    path('Driver/Assign/edit/<driver_id>', views.assign, name='assign'),
    path('Driver/Set Status/edit/<set_id>', views.aval, name='aval'),
    path('delete/<driver_id>', views.delete_drv, name='delete_drv'),
]

humanresource/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from driver.models import Vehicle



# Create your models here.
class VehicleStatus(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default='Available')
    assigned = models.CharField(max_length=50)

    def __str__(self):
        return str(self.vehicle) + self.assigned + self.status

main/forms.py
from django import forms
from driver.models import Vehicle, Driver


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = '__all__'

humanresource/views.py
from django.shortcuts import render, redirect
from driver.models import Refilling
from driver.forms import RefillingForm


# Create your views here.

def human(request):
    return render(request, 'hr_index.html', {})


def refill(request):
    ref = Refilling.objects.all()
    return render(request, 'fill requests.html', {'ref': ref})


def edit_request(request, request_id):
    if request.method == "POST":
        req = Refilling.objects.get(pk=request_id)
        form = RefillingForm(request.POST or None, instance=req)
        Refilling.objects.filter(id=request_id).update(status=request.POST['status'])
        if form.is_valid():
            instance = form.save(commit=False)
            instance.hr = request.user
        return redirect('hr:refill')
    else:
        ref = Refilling.objects.get(pk=request_id)
        return render(request, 'edit_request.html', {'ref': ref})


def maintenance(request):
    return render(request, 'basehr.html', {})

main/views.py
from django.shortcuts import render, redirect
from staff.models import Request
from staff.forms import RequestForm
from driver.models import Refilling, Vehicle, Driver, Locations
from workshop.models import Maintainance, MajorMaintainance
from accounts.models import User
from main.models import VehicleStatus
from driver.forms import RefillingForm
from workshop.forms import MaintenanceForm
from accounts.decorators import transport_required
from django.http import HttpResponse
from main.forms import VehicleForm, DriverForm
from django.core.mail import send_mail
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
import random


# Create your views here.

def transport(request):
    mapbox_access_token = 'pk.eyJ1IjoiaWRhdmVyczk4IiwiYSI6ImNrcXBzZWxmczA4Mm8ydnEzMXR3emt3eXcifQ.d-QVNcLt_5acuWmgUpBPTA'
    return render(request, 'index.html', {'mapbox_access_token': mapbox_access_token})


def requests(request):
    tripss = Request.objects.all()
    return render(request, 'request.html', {'trips': tripss})


def edit_request(request, request_id):
    if request.method == "POST":

        req = Request.objects.get(pk=request_id)
        form = RequestForm(request.POST or None, instance=req)
        # Request.objects.update(driver=request.POST['driver'])
        Request.objects.filter(id=request_id).update(driver=request.POST['driver'], approved_by=request.POST['trans'])
        sms = request.POST['driver']
        number = Request.objects.raw('select phone from driver_assigned')
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            send_mail(
                'Trip FeedBack',
                'Your Trip information is already posted login to check status',
                'davidrobert785@gmail.com',
                ['davidrobert10@ymail.com'],
                fail_silently=False
            )

        return redirect('main:requests')
    else:
        req_obj = Request.objects.get(pk=request_id)
        drv = Driver.objects.all()
        users = User.objects.all()
        print(request_id)
        return render(request, 'edit.html', {'req_obj': req_obj, 'driver': drv, 'users': users})


def status(request):
    if request.method == "POST":

        form = VehicleForm(request.POST)
        print(form)
        Vehicle.objects.create(model=request.POST['vmodel'], license=request.POST['licence'],
                               fuel_type=request.POST['fuel'],
                               manufacturer=request.POST['make'], color=request.POST['vcolor'],
                               transmission=request.POST['trans'], seats=request.POST['vseat'],
                               status=request.POST['status'],
                               body=request.POST['type'], last_refill=request.POST['refill'],
                               maintenance_record=request.POST['vmaint'],
                               operability=request.POST['op'], mileage=request.POST['milleage'])
        if form.is_valid():
            form.save()
        return redirect('main:status')
    else:
        tripss = Vehicle.objects.all()
        loc = [Locations.objects.all().last()]

        # last_date = loc.id
        return render(request, 'vehStatus.html', {'trips': tripss, 'loc': loc})


def edit_status(request, status_id):
    if request.method == "POST":

        stat = VehicleStatus.objects.get(pk=status_id)
        form = VehicleForm(request.POST or None, instance=stat)
        VehicleStatus.objects.filter(id=status_id).update(status=request.POST['status'])
        if form.is_valid():
            form.save()
        return redirect('main:status')
    else:
        stat_obj = VehicleStatus.objects.get(pk=status_id)
        print(status_id)
        return render(request, 'edit_status.html', {'stat': stat_obj})


def filling(request):
    tripss = Refilling.objects.all()
    return render(request, 'filling requests.html', {'trips': tripss})


def edit_filling(request, filling_id):
    if request.method == "POST":
        fill = Refilling.objects.get(pk=filling_id)
        form = RefillingForm(request.POST or None, instance=fill)
        Refilling.objects.filter(id=filling_id).update(number=request.POST['namba'], approved=request.POST['transport'])
        if form.is_valid():
            instance = form.save(commit=False)
            instance.received_by = request.user
        return redirect('main:filling')
    else:
        fill_obj = Refilling.objects.get(pk=filling_id)
        tro = User.objects.all()
        number = random.randint(1, 798)
        return render(request, 'edit_filling.html', {'fill': fill_obj, 'num': number, 'users': tro})


def driver(request):

    if request.method == 'POST':
        form = DriverForm(request.POST or None, request.FILES or None)

        Driver.objects.create(driver_name=request.POST['fname'],
                              vehicle=request.POST['number'], status=request.POST['status'],
                              phone=request.POST['phone'], added_by=request.POST['added_by'])
        if form.is_valid():
            form.save()

        return redirect('main:driver')
    else:
        tripss = Driver.objects.all()

        vehicle = Vehicle.objects.all()

        users = User.objects.all()
        return render(request, 'driver.html', {'trips': tripss, 'vehicle': vehicle, 'users': users})


def maintenance(request):
    main = Maintainance.objects.all()
    return render(request, 'maintenance.html', {'main': main})


def edit_main(request, main_id):
    if request.method == "POST":
        main = Maintainance.objects.get(pk=main_id)
        form = MaintenanceForm(request.POST or None, instance=main)
        Maintainance.objects.filter(id=main_id).update(transport=request.POST['transport'])
        if form.is_valid():
            form.save()
        return redirect('main:maintenance')
    else:
        main_obj = Maintainance.objects.get(pk=main_id)
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'editmain.html', {'main': main_obj, 'user': tro})


def assign(request, driver_id):
    if request.method == "POST":
        drv = Driver.objects.get(pk=driver_id)
        form = DriverForm(request.POST or None, instance=drv)
        Driver.objects.filter(id=driver_id).update(vehicle=request.POST['vehicle'])
        if form.is_valid():
            form.save()
        return redirect('main:driver')
    else:
        drv_obj = Driver.objects.get(pk=driver_id)
        veh = Vehicle.objects.all()
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'assign.html', {'drv': drv_obj, 'user': tro, 'veh': veh})


def aval(request, set_id):
    if request.method == "POST":
        drv = Driver.objects.get(pk=set_id)
        form = DriverForm(request.POST or None, instance=drv)
        Driver.objects.filter(id=set_id).update(status=request.POST['status'])
        if form.is_valid():
            form.save()
        return redirect('main:driver')
    else:
        drv_obj = Driver.objects.get(pk=set_id)
        veh = Vehicle.objects.all()
        tro = User.objects.all()
        # number = random.randint(1, 798)
        return render(request, 'setAvailable.html', {'drv': drv_obj, 'user': tro, 'veh': veh})


def delete_drv(request, driver_id):
    drv = Driver.objects.get(pk=driver_id)
    drv.delete()
    return redirect('main:driver')

humanresource/templates/basehr.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
        <title></title>
    {% endblock %}


  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'static/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'static/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'static/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'static/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'static/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'static/static/plugins/summernote/summernote-bs4.min' %}.css">

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="{% static 'static/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'static/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'static/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'static/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static 'static/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'static/plugins/toastr/toastr.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{% static 'static/dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'main:transport' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->

  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'static/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Fleet</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->


      <!-- SidebarSearch Form -->


      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="{% url 'hr:human' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard

              </p>
            </a>
          </li>
            <li class="nav-item menu-open">
            <a href="{% url 'hr:refill' %}" class="nav-link">
              <i class="nav-icon fas fa-inbox"></i>
              <p>
               Refilling Request

              </p>
            </a>
          </li>
            <li class="nav-item menu-open">
            <a href="{% url 'hr:maintenance' %}" class="nav-link">
              <i class="nav-icon fas fa-id-badge"></i>
              <p>
                 Maintenance

              </p>
            </a>
          </li>
            <li class="nav-item menu-open">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-shield-alt"></i>
              <p>
                Maintenance Reports

              </p>
            </a>
          </li>
        </ul>
      </nav>
    </div>

      <!-- /.sidebar-menu -->
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Human Resource</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
      {% block content %}




    {% endblock %}
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
     <strong>Copyright &copy; NIT/BIT/2018/806 <a href="#">DAVID R SHUGHURU</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>BIT</b> 2021
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'static/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'static/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'static/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'static/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'static/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'static/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'static/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'static/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'static/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'static/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'static/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'static/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'static/dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'static/dist/js/pages/dashboard.js' %}"></script>
<script src="{% static 'static/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'static/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'static/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'static/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'static/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'static/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
</body>
</html>

humanresource/templates/edit_request.html
{% extends 'basehr.html' %}

{% block title %}
    <title>Refill | FMS</title>

{% endblock %}

{% block content %}
                <!-- Page content-->
                <div class="container-fluid">

                    <form method="POST" style="margin-top: 50px; padding: 10px;" >
                        {% csrf_token %}


                                <div class="row">
                                        <div class="col-sm-6">
                                          <div class="form-group">
                                <label for="facility_opt">Status for Filling Request {{ ref.vehicle }}</label>
                                <select id="facility_opt" class="form-control" name="status">
                                    <option value="" disabled selected>Status</option>
                                    <option>Pending</option>
                                    <option>Approved</option>

                                </select>
                                          </div>
                                        </div>
                                </div>
                                <div><button type="submit" class="btn btn-primary">Change Status</button></div>



                    </form>





                </div>
            
        <!-- Bootstrap core JS-->
{% endblock %}

humanresource/templates/fill requests.html
{% extends 'basehr.html' %}

{% block title %}
    <title>Refill | FMS</title>

{% endblock %}

{% block content %}

<!-- Page content-->
                <div class="container-fluid">
                        <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                          <thead>
                                <tr>
                                        <th>Number</th>
                                        <th>Date</th>
                                        <th>Approved By(T.O)</th>
                                        <th>Fuel</th>
                                        <th>Liters</th>
                                        <th>Vehicle</th>
                                        <th>Approved By(H.R)</th>

                                </tr>
                              </thead>
                              <tbody>
                               {% for obj in ref %}
                                   {% if obj.number != '' and obj.approved != '' %}
                       <tr>
                                    <td>{{ obj.number }}</td>
                                    <td>{{ obj.date }}</td>
                                    <td>{{ obj.approved }}</td>
                                    <td>{{ obj.fuel }}</td>
                                    <td>{{ obj.liters }}</td>
                                    <td>{{ obj.vehicle }}</td>
                                    <td><a href="{% url 'hr:edit_request' obj.id %}">{{ obj.status }}</a></td>

                                </tr>
                                   {% endif %}
                    {% endfor %}
                              </tbody>
                <tfoot>
                <tr>
                                        <th>Number</th>
                                        <th>Date</th>
                                        <th>Approved By(T.O)</th>
                                        <th>Fuel</th>
                                        <th>Liters</th>
                                        <th>Vehicle</th>
                                        <th>Approved By(H.R)</th>
                </tr>
                </tfoot>


                </table>
                </div>
            </div>

        <!-- Bootstrap core JS-->
 {% endblock %}

humanresource/templates/hr_index.html
{% extends 'basehr.html' %}

{% block title %}
    <title>Dashboard | FMS</title>
{% endblock %}

{% block content %}

{% endblock %}

humanresource/templates/main.html
{% extends 'basehr.html' %}


{% block title %}
{% endblock %}

{% block coontent %}
        ewaaa
{% endblock %}